version: '3.8'
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb_data: 