version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    command: start --user root --pass root memory
    ports:
      - "8000:8000"
    restart: unless-stopped 
